import type { Route } from "./+types/home";
import Navbar from "../components/Navbar";
import { resumes } from "../../constants/index";
import ResumeCard from "~/components/ResumeCard";

import { useEffect } from "react";
import { useLocation, useNavigate } from "react-router";
import { usePuterStore } from "~/lib/puter";

export function meta({}: Route.MetaArgs) {
  return [
    { title: "ResumeCred" },
    { name: "description", content: "Optimize your dear Resume!" },
  ];
}

export default function Home() {

    const { auth, isLoading } = usePuterStore(); 
    const navigate = useNavigate();

    useEffect(() => {
        if(!auth.isAuthenticated && !isLoading) navigate('/auth?next=/');
    }, [auth.isAuthenticated, isLoading])

  return <main className = "bg-[url('/images/bg-main.svg')] bg-cover">
    <Navbar />


    <section className = "main-section">
      <div className = "page-heading py-16">
        <h1>Optimize Your Resume & Track The Ratings.</h1>
        <h2>Review your submissions and check feedbacks generated by AI.</h2>
      </div>

      {resumes.length > 0 && (
        <div className = "resumes-section">
          { resumes.map((resume) => (
            <ResumeCard key = {resume.id} resume = {resume} />
          ))}
        </div>
      )}
    
    </section>

    
    

  </main>
}
